### ISSUE TITLE
Clicking on Add component takes it to wrong path causing 404

### ISSUE THREAD

**Issue by theguidingstar** [strapi/strapi-plugin-seo#61]
Clicking on Add Component on SEO tab takes us to : 
https://domain/plugins/content-type-builder/content-types/api::blog.blog

Whereas the admin runs on
https://domain/admin/plugins/content-type-builder/content-types/api::blog.blog

/admin is missing from the navigation URL. 

Am I missing any configuration or it's a Bug?

**Comment by Mcastres** [comment]
Fixed in #60

**Comment by theguidingstar** [comment]
@Mcastres is this released we await the release in newer version?

**Comment by simwai** [comment]
Still happening

The URL it should take me to: http://localhost:13370/admin/content-manager/collection-types/api::blog.blog
The URL it takes me to: http://localhost:13370/plugins/content-type-builder/content-types/api::blog.blog
